name       : wire
version    : 2.11.2685
release    : 2
source     :
    - https://github.com/wireapp/wire-desktop/archive/release/2.11.2685.tar.gz : e68ccb04d1f0741e0b703c7cff37d0d208ae696bf3cbb7f2f0da9c1283d50b5f
license    : GPL-3
component  : network.im
summary    : A privacy focused instant messaging app
networking : true
description: |
    Official Client for the instant messaging service wire.com, which provides a Swiss based privacy focused service with end to end encryption.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xi)
    - pkgconfig(xscrnsaver)
    - git
    - nodejs
    - yarn
setup      : |
    npm install grunt
    yarn
    %patch -p1 < $pkgfiles/0001-Disable-building-of-AppImages-and-debs.patch
    %patch -p1 < $pkgfiles/0002-Only-build-for-x64.patch
build      : |
    ./node_modules/grunt/bin/grunt linux-prod
install    : |
    install -dm00644 $installdir/usr/share/wire/
    cp -r ./wrap/dist/linux-unpacked/* $installdir/usr/share/wire/
    install -Dm644 $pkgfiles/wire.desktop $installdir/usr/share/applications/wire.desktop
    install -Dm644 ./resources/icons/256x256.png $installdir/usr/share/icons/hicolor/256x256/apps/wire.png
    install -Dm644 ./resources/icons/32x32.png $installdir/usr/share/icons/hicolor/32x32/apps/wire.png
