name       : wire
version    : 2.15.2751
release    : 3
source     :
    - https://github.com/wireapp/wire-desktop/archive/release/2.15.2751.tar.gz : a58894b3fa8421fbce96e0a608e71b978e1d58c14c3c95fab1a29675a8c6560a
license    : GPL-3.0
component  : network.im
summary    : A privacy focused instant messaging app
networking : true
description: |
    Official Client for the instant messaging service wire.com, which provides a Swiss based privacy focused service with end to end encryption.
builddeps  :
    - alsa-lib
    - gconf
    - libgtk-2
    - libxcomposite
    - libxcursor
    - libxi
    - libxrandr
    - libxscrnsaver
    - libxtst
    - git
    - nodejs
setup      : |
    %patch -p1 < $pkgfiles/wire-make-custom-linux-builds-easier.patch
    %patch -p1 < $pkgfiles/0001-Wire-enable-asar-for-linux.patch
    npm config set unsafe-perm=true
    npm install
build      : |
    ./node_modules/grunt/bin/grunt --arch=x64 --target=dir linux-other
install    : |
    install -Dm644 $pkgfiles/wire.desktop $installdir/usr/share/applications/wire.desktop
    install -Dm644 $workdir/resources/icons/256x256.png $installdir/usr/share/icons/hicolor/256x256/apps/wire.png
    install -Dm644 $workdir/resources/icons/32x32.png $installdir/usr/share/icons/hicolor/32x32/apps/wire.png

    install -dm755 $installdir/usr/share/wire/
    cp -r $workdir/wrap/dist/linux-unpacked/* $installdir/usr/share/wire/

    install -dm755 $installdir/usr/bin
    ln -sv /usr/share/wire/wire-desktop $installdir/usr/bin/wire
