name       : wire
version    : 3.3.2872
release    : 9
source     :
    - https://github.com/wireapp/wire-desktop/archive/release/3.3.2872.tar.gz : 35949658604dbd400f3d86925b5ef3754c1ead285324dd94d2d0ed1e2d485bc4
license    : GPL-3.0-or-later
component  : network.im
summary    : A privacy focused instant messaging app
networking : true
description: |
    Official Client for the instant messaging service wire.com, which provides a Swiss based privacy focused service with end to end encryption.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gtk+-x11-2.0)
    - pkgconfig(xscrnsaver)
    - cups-devel
    - git
    - nodejs
setup      : |
    %apply_patches
    npm config set unsafe-perm=true
    npm install
build      : |
    ./node_modules/grunt/bin/grunt --arch=x64 linux-other
install    : |
    install -Dm00644 $pkgfiles/wire.desktop $installdir/usr/share/applications/wire.desktop
    install -Dm00644 $workdir/resources/icons/256x256.png $installdir/usr/share/icons/hicolor/256x256/apps/wire.png
    install -Dm00644 $workdir/resources/icons/32x32.png $installdir/usr/share/icons/hicolor/32x32/apps/wire.png

    install -dm00755 $installdir/usr/share/wire/
    cp -r $workdir/wrap/dist/linux-unpacked/* $installdir/usr/share/wire/

    install -dm00755 $installdir/usr/bin
    ln -sv /usr/share/wire/wire-desktop $installdir/usr/bin/wire
