name       : wire
version    : 3.16.2923
release    : 21
source     :
    - https://github.com/wireapp/wire-desktop/archive/linux/3.16.2923.tar.gz : c7f7d75b3c6a212c4a452a17c726b8605f39a59926d3454a38e7a303a2ed9d5c
license    : GPL-3.0-or-later
component  : network.im
summary    : A privacy focused instant messaging app
networking : true
description: |
    Official Client for the instant messaging service wire.com, which provides a Swiss based privacy focused service with end to end encryption.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xscrnsaver)
    - ffmpeg-chromium
    - git
    - yarn
setup      : |
    yarn
build      : |
    export LINUX_TARGET=dir
    yarn build:linux
install    : |
    install -Dm00644 $pkgfiles/wire.desktop $installdir/usr/share/applications/wire.desktop
    install -Dm00644 $workdir/resources/icons/256x256.png $installdir/usr/share/icons/hicolor/256x256/apps/wire.png
    install -Dm00644 $workdir/resources/icons/32x32.png $installdir/usr/share/icons/hicolor/32x32/apps/wire.png

    install -dm00755 $installdir/usr/share/wire/
    cp -r $workdir/wrap/dist/linux-unpacked/* $installdir/usr/share/wire/

    install -dm00755 $installdir/usr/bin
    ln -sv /usr/share/wire/wire-desktop $installdir/usr/bin/wire

    rm $installdir/usr/share/wire/lib{ffmpeg,EGL,GLESv2}.so

    ln -s /usr/lib64/libEGL.so $installdir/usr/share/wire/libEGL.so
    ln -s /usr/lib64/libGLESv2.so $installdir/usr/share/wire/libGLESv2.so
