name       : wire
version    : 3.31.3060
release    : 36
source     :
    - https://github.com/wireapp/wire-desktop/archive/refs/tags/linux/3.31.3060.tar.gz : 94affab5044593a9504e63aa92e5e9e3549689f80a12ef2efbcdcba92981f49e
license    : GPL-3.0-or-later
component  : network.im
homepage   : https://wire.com
summary    : A privacy focused instant messaging app
networking : true
description: |
    Official Client for the instant messaging service wire.com, which provides a Swiss based privacy focused service with end to end encryption.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gbm)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xscrnsaver)
    - git
    - yarn
setup      : |
    yarn
build      : |
    export LINUX_TARGET=dir
    yarn build:linux
install    : |
    install -Dm00644 $pkgfiles/wire.desktop $installdir/usr/share/applications/wire.desktop
    install -Dm00644 $workdir/resources/icons/256x256.png $installdir/usr/share/icons/hicolor/256x256/apps/wire.png
    install -Dm00644 $workdir/resources/icons/32x32.png $installdir/usr/share/icons/hicolor/32x32/apps/wire.png

    install -dm00755 $installdir/usr/share/wire/
    cp -r $workdir/wrap/dist/linux-unpacked/* $installdir/usr/share/wire/

    install -dm00755 $installdir/usr/bin
    ln -sv /usr/share/wire/wire-desktop $installdir/usr/bin/wire
