name       : wire
version    : 3.23.2938
release    : 29
source     :
    - https://github.com/wireapp/wire-desktop/archive/linux/3.23.2938.tar.gz : fbcc337a46816d36e089723127ad1966670e90a96c0b4417008afa20079985de
license    : GPL-3.0-or-later
component  : network.im
summary    : A privacy focused instant messaging app
networking : true
description: |
    Official Client for the instant messaging service wire.com, which provides a Swiss based privacy focused service with end to end encryption.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(gbm)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xscrnsaver)
    - git
    - yarn
setup      : |
    yarn
build      : |
    export LINUX_TARGET=dir
    yarn build:linux
install    : |
    install -Dm00644 $pkgfiles/wire.desktop $installdir/usr/share/applications/wire.desktop
    install -Dm00644 $workdir/resources/icons/256x256.png $installdir/usr/share/icons/hicolor/256x256/apps/wire.png
    install -Dm00644 $workdir/resources/icons/32x32.png $installdir/usr/share/icons/hicolor/32x32/apps/wire.png

    install -dm00755 $installdir/usr/share/wire/
    cp -r $workdir/wrap/dist/linux-unpacked/* $installdir/usr/share/wire/

    install -dm00755 $installdir/usr/bin
    ln -sv /usr/share/wire/wire-desktop $installdir/usr/bin/wire
